package org.manalith.ircbot.plugin.nvidiadrivernews;

import org.manalith.ircbot.ManalithBot;
import org.manalith.ircbot.plugin.AbstractBotPlugin;
import org.manalith.ircbot.resources.MessageEvent;

public class NvidiaDriverNewsPlugin extends AbstractBotPlugin {

	public NvidiaDriverNewsPlugin(ManalithBot bot) {
		super(bot);
		// TODO Auto-generated constructor stub
	}

	public String getName() {
		// TODO Auto-generated method stub
		return "Nvidia최신버전";
	}

	public String getNamespace() {
		// TODO Auto-generated method stub
		return "nvidia";
	}
	
	public String getHelp () 
	{
		// TODO Semi-autogenerated (<- is a lie) method stub
		return "!nvidia";
	}
	
	public void onMessage ( MessageEvent event )
	{
		String channel = event.getChannel();
		String msg = event.getMessage();
		
		if ( msg.equals("!nvidia") )
		{
			NvidiaDriverNewsRunner runner = new NvidiaDriverNewsRunner();
			bot.sendLoggedMessage(channel, runner.run());
		}
	}
}
