//
// TokenSubtype.java
// darkcircle dot 0426 at gmail dot com
//
// This source can be distributed under the terms of GNU General Public License version 3
// which is derived from the license of Manalith bot.
package org.manalith.ircbot.plugin.CER;


public enum TokenSubtype {
	TBobyOpen,
	TBodyClose,
	TROpen,
	TRClose,
	TDOpen,
	TDClose,
	DivOpen,
	DivClose,
	SpanOpen,
	SpanClose,
	EMOpen,
	EMClose,
	TextString,
	CommandHelp,
	CommandLatestRound,
	CommandForceUpdate,
	CommandShow,
	CommandConvertFrom,
	CommandConvertTo,
	CommandBuyCash,
	CommandCellCash,
	CommandSendRemittance,
	CommandRecvRemittance,
	CurrencyUSD,
	CurrencyEUR,
	CurrencyJPY,
	CurrencyCNY,
	CurrencyHKD,
	CurrencyTWD,
	CurrencyGBP,
	CurrencyCAD,
	CurrencyCHF,
	CurrencySEK,
	CurrencyAUD,
	CurrencyNZD,
	CurrencyILS,
	CurrencyDKK,
	CurrencyNOK,
	CurrencySAR,
	CurrencyKWD,
	CurrencyBHD,
	CurrencyAED,
	CurrencyJOD,
	CurrencyEGP,
	CurrencyTHB,
	CurrencySGD,
	CurrencyMYR,
	CurrencyIDR,
	CurrencyBND,
	CurrencyINR,
	CurrencyPKR,
	CurrencyBDT,
	CurrencyPHP,
	CurrencyMXN,
	CurrencyBRL,
	CurrencyVND,
	CurrencyZAR,
	CurrencyRUB,
	CurrencyHUF,
	CurrencyPLN,
	FAAll,
	FACentralRate,
	FABuyCash,
	FACellCash,
	FASendRemit,
	FARecvRemit,
	FAECRate,
	FADollarExcRate,
	AmountNatural,
	AmountFp,
	Unknown,
}
