//
// TokenSubtype.java
// darkcircle dot 0426 at gmail dot com
//
// This source can be distributed under the terms of GNU General Public License version 3
// which is derived from the license of Manalith bot.
package org.manalith.ircbot.plugin.cer2;


public enum TokenSubtype {
	TextString,
	CommandHelp,
	CommandLastRound,
	CommandShow,
	CommandConvert,
	CommandBuyCash,
	CommandCellCash,
	CommandSendRemit,
	CommandRecvRemit,
	CurrencyKRW,
	CurrencyUSD,
	CurrencyEUR,
	CurrencyJPY,
	CurrencyCNY,
	CurrencyHKD,
	CurrencyTWD,
	CurrencyGBP,
	CurrencyCAD,
	CurrencyCHF,
	CurrencySEK,
	CurrencyAUD,
	CurrencyNZD,
	CurrencyILS,
	CurrencyDKK,
	CurrencyNOK,
	CurrencySAR,
	CurrencyKWD,
	CurrencyBHD,
	CurrencyAED,
	CurrencyJOD,
	CurrencyEGP,
	CurrencyTHB,
	CurrencySGD,
	CurrencyMYR,
	CurrencyIDR,
	CurrencyBND,
	CurrencyINR,
	CurrencyPKR,
	CurrencyBDT,
	CurrencyPHP,
	CurrencyMXN,
	CurrencyBRL,
	CurrencyVND,
	CurrencyZAR,
	CurrencyRUB,
	CurrencyHUF,
	CurrencyPLN,
	FAAll,
	FACentralRate,
	FABuyCash,
	FACellCash,
	FASendRemit,
	FARecvRemit,
	FAECRate,
	FADollarExcRate,
	AmountNatural,
	AmountFp,
	Unknown,
}
